name: UuChat
main: com.rabbitown.uuchat.UuChat
version: ${version}
api-version: 1.15
author: Yoooooory
description: An easy but useful chat plugin, I think?
softdepend: [Multiverse-Core, PlayerTitle, PlaceholderAPI]

commands:
  uuchat:
    aliases: uc
    description: Plugin commands.

permissions:
  uuchat.admin:
    description: UuChat admin permission.
    children:
      uuchat.admin.reload: true
    default: op
  uuchat.bypass:
    description: UuChat bypass.
    children:
      uuchat.chat.atplayer.bypass: true
    default: false
  uuchat.chat:
    description: Allows player chat and chat with UuChat features.
    children:
      uuchat.chat.atplayer: true
    default: true