name: YaChat
main: com.rabbitown.yachat.YaChat
version: ${version}
api-version: 1.13
author: Yoooooory
description: An easy but useful chat plugin, I think?
depend: [YaLib]
softdepend: [PlaceholderAPI]

permissions:
  ycchat.admin:
    description: YaChat admin permission.
    children:
      yachat.command.reload: true
    default: op
  yachat.bypass:
    description: YaChat bypass.
    children:
      yachat.chat.atplayer.bypass: true
    default: false
  yachat.chat:
    description: Allows player chat and chat with YaChat features.
    children:
      yachat.chat.atplayer: true
    default: true