##########################
### UuChat Config Yaml ###
### Please use ยง not & ###
### Because I am lazy. ###
###   ยง == Alt + 167   ###
##########################

general:
  chat:
    pattern: 'ยงa$world_name$$player_level$ $player_title$$player_name$ > $message$'
    functions: ['atplayer']
    placeholder: false